# name: captioning_model
# channels:
#   - defaults
# dependencies:
# - python>=3.8
# - pip>=21
# - scikit-image=0.18.1
# - pip:
#    - transformers~=4.10.2
#    - ftfy
#    - regex
#    - tqdm
#    - git+https://github.com/openai/CLIP.git
#    - opencv-python~=4.5.4
#    - https://download.pytorch.org/whl/cu113/torch-1.10.0%2Bcu113-cp39-cp39-linux_x86_64.whl
#    - pyscenedetect

name: clip_prefix_caption
channels:
  - defaults
dependencies:
- python>=3.8
- pip>=21
- scikit-image=0.18.1
- pip:
   - transformers~=4.10.2
   - ftfy
   - regex
   - tqdm
   - git+https://github.com/openai/CLIP.git